/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_claydonkey_algorithms_MainActivity */

#ifndef _Included_com_claydonkey_algorithms_MainActivity
#define _Included_com_claydonkey_algorithms_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_claydonkey_algorithms_MainActivity_BIND_ABOVE_CLIENT
#define com_claydonkey_algorithms_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_claydonkey_algorithms_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_claydonkey_algorithms_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_claydonkey_algorithms_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_claydonkey_algorithms_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_claydonkey_algorithms_MainActivity_BIND_AUTO_CREATE
#define com_claydonkey_algorithms_MainActivity_BIND_AUTO_CREATE 1L
#undef com_claydonkey_algorithms_MainActivity_BIND_DEBUG_UNBIND
#define com_claydonkey_algorithms_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_claydonkey_algorithms_MainActivity_BIND_IMPORTANT
#define com_claydonkey_algorithms_MainActivity_BIND_IMPORTANT 64L
#undef com_claydonkey_algorithms_MainActivity_BIND_NOT_FOREGROUND
#define com_claydonkey_algorithms_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_claydonkey_algorithms_MainActivity_BIND_WAIVE_PRIORITY
#define com_claydonkey_algorithms_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_claydonkey_algorithms_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_claydonkey_algorithms_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_claydonkey_algorithms_MainActivity_CONTEXT_INCLUDE_CODE
#define com_claydonkey_algorithms_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_claydonkey_algorithms_MainActivity_CONTEXT_RESTRICTED
#define com_claydonkey_algorithms_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_claydonkey_algorithms_MainActivity_MODE_APPEND
#define com_claydonkey_algorithms_MainActivity_MODE_APPEND 32768L
#undef com_claydonkey_algorithms_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_claydonkey_algorithms_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_claydonkey_algorithms_MainActivity_MODE_MULTI_PROCESS
#define com_claydonkey_algorithms_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_claydonkey_algorithms_MainActivity_MODE_PRIVATE
#define com_claydonkey_algorithms_MainActivity_MODE_PRIVATE 0L
#undef com_claydonkey_algorithms_MainActivity_MODE_WORLD_READABLE
#define com_claydonkey_algorithms_MainActivity_MODE_WORLD_READABLE 1L
#undef com_claydonkey_algorithms_MainActivity_MODE_WORLD_WRITEABLE
#define com_claydonkey_algorithms_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_DIALER
#define com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_DISABLE
#define com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_claydonkey_algorithms_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_claydonkey_algorithms_MainActivity_RESULT_CANCELED
#define com_claydonkey_algorithms_MainActivity_RESULT_CANCELED 0L
#undef com_claydonkey_algorithms_MainActivity_RESULT_FIRST_USER
#define com_claydonkey_algorithms_MainActivity_RESULT_FIRST_USER 1L
#undef com_claydonkey_algorithms_MainActivity_RESULT_OK
#define com_claydonkey_algorithms_MainActivity_RESULT_OK -1L
/*
 * Class:     com_claydonkey_algorithms_MainActivity
 * Method:    markovArrayResult
 * Signature: (DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_claydonkey_algorithms_MainActivity_markovArrayResult
  (JNIEnv *, jobject, jdouble, jint, jint);

/*
 * Class:     com_claydonkey_algorithms_MainActivity
 * Method:    markovArrayDim
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_claydonkey_algorithms_MainActivity_markovArrayDim
  (JNIEnv *, jobject);

/*
 * Class:     com_claydonkey_algorithms_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_claydonkey_algorithms_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
